#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[[ -n "$1" ]] && TEST_TARGET="$DIR/$1" || TEST_TARGET="$DIR"

phpunit --colors --coverage-html $DIR/coverage-report --bootstrap $DIR/_bootstrap.php $TEST_TARGET

