#!/bin/bash

SCRIPTPATH=`which $0`
TESTDIRECTORY=`dirname $SCRIPTPATH`;

cd $TESTDIRECTORY;

TESTDIRECTORY=`pwd`

phpunit --bootstrap $TESTDIRECTORY/_bootstrap.php \
    --testdox \
    $TESTDIRECTORY/MasterTestSuite.php

