#!/bin/bash

SCRIPTPATH=`which $0`
TESTDIRECTORY=`dirname $SCRIPTPATH`;

cd $TESTDIRECTORY;

TESTDIRECTORY=`pwd`

phpunit --colors --bootstrap \
    $TESTDIRECTORY/_bootstrap.php $TESTDIRECTORY/MasterTestSuite.php

