#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

[[ -n "$1" ]] && TEST_TARGET="$DIR/$1" || TEST_TARGET="$DIR"

phpunit --colors --testdox-text $DIR/bdd-style-docs.txt --bootstrap $DIR/_bootstrap.php $TEST_TARGET

